### ISSUE TITLE
Oracle.ManagedDataAccess.Client.OracleException: 'Connection request timed out'

### ISSUE THREAD

**Issue by melihkeskin** [CrazyJson/Citms.EntityFrameworkCore.Oracle#1]
![image](https://user-images.githubusercontent.com/11782116/40363224-97e3f880-5dd7-11e8-99e5-4bdafcf2882c.png)

Hello,
thanks for sharing.
I want to ask a question.
How can i resolve on the picture?
Can you help me ?

**Comment by CrazyJson** [comment]
Make sure that your database connection string is correct, and you can use the Oracle.ManagedDataAccess driver in the.Net Framework project to verify whether the connection string has a problem.

**Comment by melihkeskin** [comment]
Thanks for replay.
i am looking for it.
also
can i execute raw sql ?
Something like "SELECT * FROM ...."

**Comment by CrazyJson** [comment]
[EF Core Extend.zip](https://github.com/CrazyJson/Citms.EntityFrameworkCore.Oracle/files/2027004/EF.Core.Extend.zip)
![1](https://user-images.githubusercontent.com/8163485/40367633-783d4a38-5e0c-11e8-827a-f8d555ac3211.jpg)

In view of the need to execute SQL using EF Core, I wrote a related development method.
`            db.Database.Query<Spotting>("select * from common_spotting where spottingId=:a", 
                    new { a = "123" });
                db.Database.ToSingle<Spotting>("select * from common_spotting where spottingId=:a",
                    new { a = "123" });`

**Comment by melihkeskin** [comment]
thank you very much. 👍
