### ISSUE TITLE
linq group by 查询时生成的sql没有group by

### ISSUE THREAD

**Issue by ihuangxing** [CrazyJson/Citms.EntityFrameworkCore.Oracle#23]
**c#代码**
![image](https://user-images.githubusercontent.com/39799189/57512471-5142a700-733e-11e9-9c1d-d35a7fc758c8.png)

**执行错误日志**
![image](https://user-images.githubusercontent.com/39799189/57512369-02950d00-733e-11e9-8da7-2e45b2b44d12.png)

**正确的sql应该为**

SELECT * FROM(
    SELECT "A"."ID", "A"."BPMNBYTES", "A"."CATALOGID", "A"."CHECKOUTTIME", "A"."CHECKOUTUSER", "A"."COMMENTS", "A"."CREATEDBY", "A"."CREATEDTIME", "A"."ENGINEVERSION", "A"."ISRECYCLABLED", "A"."PROCESSDEFID", "A"."PROCESSIMAGE", "A"."PROCESSNAME", "A"."PROCESSVERSION", "A"."STATUS", "A"."TENANTID", "A"."UPDATEDBY", "A"."UPDATEDTIME", "T"."PRONAME", "T"."PROSTATUS", "T"."PROVERSION",rownum RN 
FROM "DEVPROCESSMODEL" "A"
INNER JOIN (
    SELECT "D"."PROCESSNAME" "PRONAME", MAX("D"."STATUS") "PROSTATUS", MAX("D"."PROCESSVERSION") "PROVERSION"
    FROM "DEVPROCESSMODEL" "D" `GROUP BY "D"."PROCESSNAME"`
) "T" ON (("A"."PROCESSNAME" = "T"."PRONAME") AND ("A"."PROCESSVERSION" = "T"."PROVERSION")) AND ("A"."STATUS" = "T"."PROSTATUS")
ORDER BY "A"."ID" DESC
) WHERE rownum <=1 and  RN > 10

**Comment by ihuangxing** [comment]
@CrazyJson 在线等啊-_-!!!

**Comment by ihuangxing** [comment]
![image](https://user-images.githubusercontent.com/39799189/57517570-ba7be780-7349-11e9-8f80-6e6a62375f88.png)

在源码中调试发现少了这段，请尽快修复掉。

**Comment by CrazyJson** [comment]
已发布1.0.8版本

**Comment by ihuangxing** [comment]
@CrazyJson 我本地源码还修改了一个地方，请帮我看下是否合理：
![image](https://user-images.githubusercontent.com/39799189/57664565-3ff1e700-762b-11e9-8860-9d9621b7a7fc.png)
修改原因为：
![image](https://user-images.githubusercontent.com/39799189/57664633-94956200-762b-11e9-8d16-0d28524ea1af.png)
生成的语句：
![image](https://user-images.githubusercontent.com/39799189/57664685-c9091e00-762b-11e9-8322-3148eff06490.png)
