### ISSUE TITLE
is there any solution to excute stored procedure by Citms.EntityFramework? 

### ISSUE THREAD

**Issue by albertLees** [CrazyJson/Citms.EntityFrameworkCore.Oracle#3]
is there any solution to excute stored procedure by Citms.EntityFramework?

**Comment by huybn5776** [comment]
Is that what you want?
[Entity Framework Core 2 – Scalar function mapping](http://anthonygiretti.com/2018/01/11/entity-framework-core-2-scalar-function-mapping/)

**Comment by CrazyJson** [comment]
`                var cmd = db.Database.GetDbConnection().CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = procName;
                OracleParameter guest_type = new OracleParameter(":i_guest_type", OracleDbType.Int32);
                guest_type.Value = 10;
                guest_type.Direction = ParameterDirection.Input;
                cmd.Parameters.Add(guest_type);
                cmd.Connection.Open();
                //int retCode = cmd.ExecuteNonQuery();
                var reader = cmd.ExecuteReader();
                cmd.Connection.Close();`

**Comment by CrazyJson** [comment]
``
