### ISSUE TITLE
Plans for updating to 2.1

### ISSUE THREAD

**Issue by ghost** [CrazyJson/Citms.EntityFrameworkCore.Oracle#4]
Hi,

The code doesn't currently work on .NET Core 2.1 because of the use of some EF internal methods that were removed.

I've noticed that there's a pull request from @huybn577 that does some changes but I don't know if those are the only ones required.

Do you have any plans for upgrading the library to 2.1, need any help?

**Comment by CrazyJson** [comment]
At present, many people have proposed to upgrade the library version to 2.1, and I will start the upgrade plan of version 2.1 this weekend.
If I have any problems, I will ask you for advice in time.

**Comment by tiptopdevelopment** [comment]
First of all, I want to thank you for your awesome work! 

And yes, I also can't wait for version 2.1....  I would love to use it with the latest aspnet.core 2.1

**Comment by dhruvanmurthy** [comment]
I am facing an issue similar to the one detailed [here](https://github.com/aspnet/EntityFrameworkCore/issues/11078). Is this thread discussing the same issue? or should I open a new one?

In either case any workaround would be much appreciated. Thanks in advance.

**Comment by tiptopdevelopment** [comment]
@dhruvanmurthy one of branches has 2.0 or 2.1 in it. You can grab that code and compile. Works for me, but I would prefer "official" release on github

**Comment by dhruvanmurthy** [comment]
@tiptopdevelopment Thanks. [dev2.1](https://github.com/CrazyJson/Citms.EntityFrameworkCore.Oracle/tree/dev2.1) doesn't compile, looks like some conflicts in [Program.cs](https://github.com/CrazyJson/Citms.EntityFrameworkCore.Oracle/commit/8e79204e78ee43c767c89233a9e29f2c710259f4#diff-20b2c3a4ad32c402351be668ab50ccc9) hasn't been resolved, but [dev](https://github.com/CrazyJson/Citms.EntityFrameworkCore.Oracle/tree/dev) worked for me.

I would still have to wait for "official" release though. @CrazyJson any plans of releasing a preview at least?

**Comment by CrazyJson** [comment]
Has been upgraded to the latest version
