### ISSUE TITLE
core 2.0 下 执行报错

### ISSUE THREAD

**Issue by gitub5** [CrazyJson/Citms.EntityFrameworkCore.Oracle#5]

**Comment by gitub5** [comment]
System.MissingMethodException:“Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Command>, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.”

**Comment by bingxueyinlian** [comment]
core 2.1下也报同样的错

**Comment by hmuhdkamran** [comment]
I am facing the same issue `Application startup exception: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Command>, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
   at Microsoft.EntityFrameworkCore.Oracle.Storage.Internal.OracleRelationalCommandBuilderFactory..ctor(IDiagnosticsLogger`1 logger, IRelationalTypeMapper typeMapper)`

It will be very appreciated if it is resolve as soon as possable.

**Comment by PedroS11** [comment]
So am I, is there any solution for this problem?

**Comment by CrazyJson** [comment]
已解决
resolved
